export const taxpayerType = [
  {
    label: 'FILER',
    value: 'FILER',
  },
  { label: 'NON-FILER', value: 'NON-FILER' },
]
export const vehiclePurchaseType = [
  {
    label: 'LOCAL',
    value: 'LOCAL',
  },
  { label: 'IMPORTED', value: 'IMPORTED' },
  { label: 'AUCTIONED', vlaue: 'AUCTIONED' },
]
export const vehicleBodyType = [
  {
    label: 'MOTORCYLCE',
    value: 'MOTORCYCLE',
  },
  {
    label: 'MOTOR CAR',
    value: 'MOTOR CAR',
  },
  {
    label: 'PICKUP',
    value: 'PICKUP',
  },
  {
    label: 'VAN',
    value: 'VAN',
  },
  {
    label: 'JEEP',
    value: 'JEEP',
  },
  {
    label: 'MINI BUS',
    value: 'MINI BUS',
  },
  {
    label: 'BUS',
    value: 'BUS',
  },
  {
    label: 'TRUCK',
    value: 'TRUCK',
  },
]
export const vehicleCategories = [
  {
    label: 'PRIVATE',
    value: 'PRIVATE',
  },
  {
    label: 'GOVERNMENT',
    value: 'GOVERNMENT',
  },
  {
    label: 'COMMERCIAL',
    value: 'COMMERCIAL',
  },
]
export const vehicleCommercialCategories = [
  {
    label: 'PASSENGER VEHICLE',
    value: 'PASSENGER VEHICLE',
  },
  {
    label: 'GOODS VEHICLE',
    value: 'GOODS VEHICLE',
  },
]
export const countries = [
  'AFGHANISTAN',
  'ALGERIA',
  'ARGENTINA',
  'AUSTRALIA',
  'AUSTRIA',
  'AZERBAIJAN',
  'BAHRAIN',
  'BANGLADESH',
  'BELGIUM',
  'BENGHAZI',
  'BOSNIA AND HERZEGOVINA',
  'BRAZIL',
  'BRITAIN',
  'BRUNEI DARUSSALAM',
  'BULGARIA',
  'BURMA',
  'CANADA',
  'CEYLON (SRI LANKA)',
  'CHINA',
  'CUBA',
  'CYPRUS',
  'CZECH',
  'CZECHOSLOVAKIA',
  'DENMARK',
  'DOHA',
  'DUBAI',
  'EGYPTE',
  'ERITREA',
  'EUROPE',
  'F.R. GERMANY',
  'FINLAND',
  'FRANCE',
  'G.D.R',
  'GERMANY',
  'GHANA',
  'GREECE',
  'H.C. FOR MAURITIUS',
  'HELLENIC',
  'HONGKONG',
  'HUNGARY',
  'I.C.C',
  'IDBYA',
  'INCHON',
  'INDIA',
  'INDONESIA',
  'IRAN',
  'IRAQ',
  'ITALY',
  'JAMAHIRIYA',
  'JAPAN',
  'JORDAN',
  'JORDON',
  'KANDA',
  'KAZAKHSTAN',
  'KENYA',
  'KOREA',
  'KURGYZSTAN',
  'KUWAIT',
  'KYRGYZ',
  'LEBANON',
  'LIBYA',
  'MALAYSIA',
  'MALDIVE',
  'MARITIUS',
  'MEXICO',
  'MOROCCO',
  'MYANMAR',
  'NEPAL',
  'NETHERLAND (HOLLAND)',
  'NEWZEALAND',
  'NIGERIA',
  'NORTH KOREA (DPRK)',
  'NORWAY',
  'NOT DECLARED',
  'OMAN',
  'OTHER',
  'P.L.O',
  'PAKISTAN',
  'PALESTINE',
  'PARIS',
  'PHILLIPINES',
  'POLAND',
  'PORTUGAL',
  'QATAR',
  'ROMANIA',
  'RUSSIA',
  'S. AGENCIES OF UNITED NATION',
  'SAUDI ARABIA',
  'SINGAPUR',
  'SINGAPURE',
  'SOMALIA',
  'SOUTH AFRICA',
  'SOUTH KOREA (C.G.K)',
  'SPAIN',
  'SRI LANKA',
  'SUDAN',
  'SWEDEN',
  'SWITZERLAND',
  'SYRIA',
  'TAJAKISTAN',
  'THAILAND',
  'TUNISIA',
  'TURKEY',
  'U.A.R (EGYPT)',
  'U.K',
  'U.S.A (AMERICA)',
  'U.S.S.R',
  'UAE',
  'UKRAINE',
  'ULSAN',
  'UNITED ARAB EMIRATES (U.A.E)',
  'UNITED NATIONS',
  'UZBEKISTAN',
  'VIETNAM',
  'WORLD BANK',
  'YEMEN',
  'YUGOSLAVIA',
]

export const districts = [
  'ABBOTABAD',
  'ATTOCK',
  'AURKAZAI AGENCY',
  'AWARAN',
  'AZAD JAMMU KASHMIR',
  'BADIN',
  'BAGH',
  'BAHAWAL NAGAR',
  'BAHAWALNAGAR',
  'BAHAWALPUR',
  'BAJAUR AGENCY',
  'BANNU',
  'BATTAGRAM',
  'BENAZIR ABAD',
  'BHAKHAR',
  'BHIMBER',
  'BONAIR',
  'BULTISTAN',
  'BUNER',
  'CHAGAI',
  'CHAGHI',
  'CHAK SAWARI',
  'CHAKWAL',
  'CHAMAN',
  'CHARSADDA',
  'CHINIOT',
  'CHITRAL',
  'D G KHAN',
  'D I KHAN',
  'DADU',
  'DERA BUGHTI',
  'DIAMIR',
  'DIR',
  'FAISALABAD',
  'GAWADAR',
  'GHANCHE',
  'GHIZAR',
  'GHOTKI',
  'GILGIT',
  'GUJRANWALA',
  'GUJRAT',
  'HAFIZABAD',
  'HANGU',
  'HARIPUR',
  'HATIANBALA',
  'HAZARA',
  'HYDERABAD',
  'ISLAMABAD',
  'JACOBABAD',
  'JAFFARABAD',
  'JAMSHORO',
  'JHANG',
  'JHELUM',
  'KALAT',
  'KALU',
  'KAMAL AGENCY',
  'KAMBERSHAHDAD KOT',
  'KARACHI',
  'KARAK',
  'KASHMOOR',
  'KASUR',
  'KECH',
  'KHAIRPUR',
  'KHANEWAL',
  'KHARAN',
  'KHUSHAB',
  'KHUZDAR',
  'KHYBER AGENCY',
  'KILLA ABDULLAH',
  'KOHAT',
  'KOHISTAN',
  'KOHLU',
  'KOTLI',
  'KRCHHI',
  'KURAM AGENCY',
  'LAHORE',
  'LAKKI MARWAT',
  'LANDI KOTAL',
  'LARKANA',
  'LASBELA',
  'LAYYAH',
  'LODHRAN',
  'LORALAI',
  'MAKRAN',
  'MALAKAND AGENCY',
  'MALEER',
  'MANDI BAHAUDDIN',
  'MANSEHRA',
  'MARDAN',
  'MARI BUGTI',
  'MEKRAN',
  'MERA MANDA KHEL',
  'MIANWALI',
  'MIRPUR',
  'MIRPURKHAS',
  'MOHMAND AGENCY',
  'MULTAN',
  'MUSA KHAIL',
  'MUSTONG',
  'MUZAFFARABAD',
  'MUZAFFARGARH',
  'NANKANA SAHIB',
  'NAROWAL',
  'NASIRABAD',
  'NAUSHAHRO FEROZE',
  'NAUSHEROFEROZ',
  'NAWABSHAH',
  'NEW AGENCY',
  'NORTH WAZIRISTAN AGE',
  'NOWSHERA',
  'OKARA',
  'OPAKZAI',
  'ORAK ZAI AGENCY',
  'PAKPATTAN',
  'PANJGUR',
  'PARACHANAR',
  'PESHAWAR',
  'PISHIN',
  'POONCH',
  'QASOOR',
  'QILLA ABDULLAH',
  'QILLA SAIF ULLAH',
  'QUETTA',
  'RAHIM YAR KHAN',
  'RAJANPUR',
  'RAWALA KOT',
  'RAWALPINDI',
  'SADHONOTI',
  'SAHIWAL',
  'SANGHAR',
  'SARGODHA',
  'SHADAE KOT',
  'SHAH BANDAR',
  'SHANGLA',
  'SHEIKHUPURA',
  'SHERANI',
  'SHIKARPUR',
  'SIALKOT',
  'SIBI',
  'SIDHNOTI',
  'SKARDU',
  'SOUTH WIZARISTAN',
  'SUKKAR',
  'SWABI',
  'SWAT',
  'TALA GANG',
  'TANK',
  'THARPARKAR',
  'THATTA',
  'TOBA TEK SINGH',
  'TUMBO',
  'TURBAT',
  'VANA',
  'VEHARI',
  'WAZIR ABAD',
  'WAZIRISTAN AGENCY',
  'ZHOB',
  'ZIARAT',
]
